import { useState, type FormEvent } from "react";
import { Plus, ShieldCheck, Users } from "lucide-react";
import { useAddWorkspaceMember, useCreateTeam } from "@/hooks/useProjects";
import type { Workspace } from "@/types";

export function AdminPanel({ workspaces, direction }: { workspaces: Workspace[]; direction: "rtl" | "ltr" }) {
  const workspace = workspaces[0], rtl = direction === "rtl";
  const [teamName, setTeamName] = useState(""), [email, setEmail] = useState(""), [role, setRole] = useState("viewer");
  const createTeam = useCreateTeam(), addMember = useAddWorkspaceMember();
  if (!workspace) return <Empty text={rtl ? "אין סביבת עבודה." : "No workspace."} />;
  const canAdmin = ["owner", "admin"].includes(workspace.role);
  function submitTeam(event: FormEvent) { event.preventDefault(); if (teamName.trim()) createTeam.mutate({ workspaceId: workspace.id, name: teamName.trim() }, { onSuccess: () => setTeamName("") }); }
  function submitMember(event: FormEvent) { event.preventDefault(); if (email.trim()) addMember.mutate({ workspaceId: workspace.id, email: email.trim(), role }, { onSuccess: () => setEmail("") }); }
  return <div className="grid gap-5 lg:grid-cols-2">
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="size-5 text-indigo-600" /><div><h2 className="font-bold">{workspace.name}</h2><p className="text-xs text-slate-400">{rtl ? "התפקיד שלך" : "Your role"}: {workspace.role}</p></div></div><div className="mt-5 space-y-2">{workspace.members.map((member) => <div key={member.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-3"><span className="grid size-8 place-items-center rounded-full bg-indigo-100 text-xs font-bold text-indigo-700">{member.name.split(" ").map((part) => part[0]).join("").slice(0,2)}</span><div className="min-w-0"><p className="truncate text-sm font-semibold">{member.name}</p><p className="truncate text-xs text-slate-400">{member.email}</p></div><span className="ms-auto rounded-lg bg-white px-2 py-1 text-[10px] font-bold text-slate-500">{member.role}</span></div>)}</div>{canAdmin && <form onSubmit={submitMember} className="mt-4 grid grid-cols-[1fr_auto_auto] gap-2"><input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder={rtl ? "כתובת Google" : "Google account email"} className="min-w-0 rounded-xl border px-3 text-xs" /><select value={role} onChange={(e) => setRole(e.target.value)} className="rounded-xl border px-2 text-xs"><option value="viewer">viewer</option><option value="editor">editor</option><option value="admin">admin</option></select><button disabled={addMember.isPending} className="grid size-10 place-items-center rounded-xl bg-indigo-600 text-white disabled:opacity-50"><Plus className="size-4" /></button></form>}{addMember.isSuccess && <p className="mt-2 text-xs text-emerald-600">{rtl ? "ההזמנה נשמרה. המשתמש יוכל להתחבר עם Google." : "Invitation saved. The user can now sign in with Google."}</p>}{addMember.isError && <p className="mt-2 text-xs text-rose-600">{rtl ? "לא ניתן היה לשמור את ההזמנה." : "The invitation could not be saved."}</p>}</section>
    <section className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><Users className="size-5 text-indigo-600" /><h2 className="font-bold">{rtl ? "צוותים" : "Teams"}</h2></div><div className="mt-4 space-y-2">{workspace.teams.map((team) => <div key={team.id} className="rounded-xl bg-slate-50 p-3 text-sm font-semibold">{team.name}</div>)}{!workspace.teams.length && <p className="py-6 text-center text-xs text-slate-400">{rtl ? "אין עדיין צוותים." : "No teams yet."}</p>}</div>{canAdmin && <form onSubmit={submitTeam} className="mt-4 flex gap-2"><input value={teamName} onChange={(e) => setTeamName(e.target.value)} placeholder={rtl ? "שם צוות" : "Team name"} className="min-w-0 flex-1 rounded-xl border px-3 text-sm" /><button className="grid size-10 place-items-center rounded-xl bg-indigo-600 text-white"><Plus className="size-4" /></button></form>}</section>
  </div>;
}
function Empty({ text }: { text: string }) { return <div className="rounded-2xl border border-dashed bg-white py-20 text-center text-sm text-slate-400">{text}</div>; }
