import { Camera, RotateCcw } from "lucide-react";
import { useState, type ChangeEvent } from "react";
import { useAuth } from "@/auth/AuthContext";
import { useToast } from "@/components/feedback/Toast";

const CHARACTERS = ["🧑‍💻", "👩‍🚀", "🦸", "🧙", "🥷", "🤖", "🦊", "🐼"];

export function AvatarSettings({ direction }: { direction: "rtl" | "ltr" }) {
  const { user, setAvatar } = useAuth(); const { notify } = useToast(); const [busy, setBusy] = useState(false); const rtl = direction === "rtl";
  async function save(avatar: string | null) { setBusy(true); try { await setAvatar(avatar); notify(rtl ? "תמונת הפרופיל עודכנה." : "Profile picture updated."); } catch { notify(rtl ? "לא ניתן היה לעדכן את תמונת הפרופיל." : "Could not update the profile picture.", "error"); } finally { setBusy(false); } }
  function upload(event: ChangeEvent<HTMLInputElement>) { const file = event.target.files?.[0]; event.target.value = ""; if (!file) return; if (!/^image\/(png|jpeg|webp)$/.test(file.type) || file.size > 512 * 1024) { notify(rtl ? "יש לבחור PNG, JPEG או WebP עד 512KB." : "Choose a PNG, JPEG, or WebP up to 512KB.", "error"); return; } const reader = new FileReader(); reader.onload = () => void save(String(reader.result)); reader.readAsDataURL(file); }
  const fallback = user?.name?.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase() || "?";
  return <section className="rounded-[20px] border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-wrap items-center gap-4"><span className="grid size-16 shrink-0 place-items-center overflow-hidden rounded-full bg-gradient-to-br from-blue-600 to-indigo-600 text-xl font-extrabold text-white shadow-md ring-4 ring-blue-50">{user?.avatar?.startsWith("data:image/") ? <img src={user.avatar} alt="" className="size-full object-cover" /> : user?.avatar ? <span className="text-3xl">{user.avatar}</span> : fallback}</span><div><h2 className="font-display text-lg font-extrabold text-slate-950">{rtl ? "תמונת פרופיל" : "Profile picture"}</h2><p className="mt-1 text-xs text-slate-400">{rtl ? "העלו תמונה או בחרו דמות מוכנה." : "Upload an image or choose a character."}</p></div><label className="ms-auto inline-flex cursor-pointer items-center gap-2 rounded-xl bg-[#0B3FC1] px-4 py-2.5 text-xs font-bold text-white shadow-sm hover:bg-[#0936A6]"><Camera className="size-4" />{rtl ? "העלאה מהמחשב" : "Upload image"}<input type="file" accept="image/png,image/jpeg,image/webp" onChange={upload} disabled={busy} className="sr-only" /></label></div><div className="mt-5 flex flex-wrap items-center gap-2">{CHARACTERS.map((avatar) => <button key={avatar} type="button" onClick={() => void save(avatar)} disabled={busy} className={`grid size-11 place-items-center rounded-full text-2xl transition hover:-translate-y-0.5 hover:bg-blue-50 ${user?.avatar === avatar ? "bg-blue-50 ring-2 ring-[#0B3FC1] ring-offset-2" : "bg-slate-50"}`}>{avatar}</button>)}<button type="button" onClick={() => void save(null)} disabled={busy} className="ms-1 inline-flex h-11 items-center gap-2 rounded-full border border-slate-200 bg-white px-4 text-xs font-bold text-slate-500 hover:bg-slate-50"><RotateCcw className="size-3.5" />{rtl ? "ראשי תיבות" : "Initials"}</button></div></section>;
}
