import { Bell, CalendarDays, ChevronDown, Filter, Link2, Moon, Plus, Search, Sun, Tags, Users, X } from "lucide-react";
import { useAuth } from "@/auth/AuthContext";
import { CATEGORY_LABELS, LINK_CATEGORIES, type Notification } from "@/types";

interface HeaderProps { search: string; onSearchChange: (value: string) => void; onNewProject: () => void; onNewLink: () => void; direction: "rtl" | "ltr"; onDirectionChange: () => void; tagFilter: string; onTagFilterChange: (value: string) => void; categoryFilter: string; onCategoryFilterChange: (value: string) => void; tags: string[]; unreadCount: number; notifications: Notification[]; theme: "light" | "dark"; onThemeChange: () => void; }

export function Header({ search, onSearchChange, onNewProject, onNewLink, direction, onDirectionChange, tagFilter, onTagFilterChange, categoryFilter, onCategoryFilterChange, tags, unreadCount, notifications, theme, onThemeChange }: HeaderProps) {
  const { user, logout } = useAuth();
  const initials = (user?.name || "User").split(" ").map((part) => part[0]).join("").slice(0, 2);
  return <header className="workspace-header sticky top-0 z-30 border-b border-slate-200 bg-white/90 backdrop-blur-xl">
    <div className="flex min-h-14 flex-wrap items-center gap-2 px-4 py-2 xl:px-5">
      <div className="relative min-w-[15rem] flex-1 xl:max-w-md"><Search className="pointer-events-none absolute start-3 top-1/2 size-3.5 -translate-y-1/2 text-slate-400" /><input type="search" value={search} onChange={(e) => onSearchChange(e.target.value)} placeholder={direction === "rtl" ? "חיפוש קישורים, פרויקטים ואנשים..." : "Search links, projects and people..."} aria-label="Global search" className="h-9 w-full rounded-lg border border-slate-200 bg-white pe-16 ps-9 text-xs outline-none transition focus:border-slate-400 focus:ring-2 focus:ring-slate-100" />{search ? <button onClick={() => onSearchChange("")} className="absolute end-3 top-1/2 -translate-y-1/2 rounded p-1 text-slate-400 hover:bg-slate-100"><X className="size-3" /></button> : <kbd className="absolute end-3 top-1/2 -translate-y-1/2 rounded border border-slate-200 bg-slate-50 px-1.5 py-0.5 text-[9px] text-slate-400">Ctrl K</kbd>}</div>
      <div className="hidden items-center gap-2 lg:flex"><FilterSelect icon={Tags} value={tagFilter} onChange={onTagFilterChange} label={direction === "rtl" ? "כל התגיות" : "All tags"} options={tags.map((tag) => [tag, tag])} /><FilterSelect icon={Filter} value={categoryFilter} onChange={onCategoryFilterChange} label={direction === "rtl" ? "כל הקטגוריות" : "All categories"} options={LINK_CATEGORIES.map((category) => [category, direction === "rtl" ? CATEGORY_LABELS[category] : category])} /></div>
      <div className="ms-auto flex items-center gap-2"><button onClick={onThemeChange} className="grid size-10 place-items-center rounded-xl border border-slate-200 text-slate-500 transition hover:bg-slate-50 hover:text-slate-900" title={direction === "rtl" ? (theme === "dark" ? "מצב בהיר" : "מצב כהה") : (theme === "dark" ? "Light mode" : "Dark mode")} aria-label={theme === "dark" ? "Switch to light mode" : "Switch to dark mode"}>{theme === "dark" ? <Sun className="size-4.5" /> : <Moon className="size-4.5" />}</button><div className="group/notifications relative"><button className="relative grid size-10 place-items-center rounded-xl border border-slate-200 text-slate-500 transition hover:bg-slate-50 hover:text-slate-900" aria-label="Notifications"><Bell className="size-4.5" />{unreadCount > 0 && <span className="absolute end-1 top-1 grid min-w-4 place-items-center rounded-full bg-rose-500 px-1 text-[9px] font-bold text-white">{unreadCount}</span>}</button><div className="invisible absolute end-0 top-full z-50 mt-1 w-72 rounded-xl border border-slate-200 bg-white p-3 opacity-0 shadow-xl group-focus-within/notifications:visible group-focus-within/notifications:opacity-100 group-hover/notifications:visible group-hover/notifications:opacity-100"><h3 className="mb-2 text-xs font-bold">{direction === "rtl" ? "התראות" : "Notifications"}</h3>{notifications.length ? <div className="space-y-1">{notifications.map((item) => <div key={item.id} className="rounded-lg bg-slate-50 p-2 text-xs text-slate-600">{item.message}</div>)}</div> : <p className="py-6 text-center text-xs text-slate-400">{direction === "rtl" ? "אין התראות." : "No notifications."}</p>}</div></div><button onClick={onNewLink} className="hidden h-10 items-center gap-2 rounded-xl border border-indigo-200 bg-indigo-50 px-3 text-xs font-bold text-indigo-700 transition hover:bg-indigo-100 sm:flex"><Link2 className="size-4" />{direction === "rtl" ? "קישור חדש" : "New Link"}</button><button onClick={onNewProject} className="flex h-10 items-center gap-2 rounded-xl bg-indigo-600 px-3.5 text-xs font-bold text-white shadow-sm transition hover:-translate-y-0.5 hover:bg-indigo-700 hover:shadow-md"><Plus className="size-4" />{direction === "rtl" ? "פרויקט חדש" : "New Project"}</button>
        <div className="group relative"><button className="flex items-center gap-2 rounded-xl p-1.5 transition hover:bg-slate-50" aria-label="User menu"><span className="grid size-8 place-items-center rounded-lg bg-gradient-to-br from-indigo-500 to-violet-600 text-xs font-bold text-white">{initials}</span><ChevronDown className="hidden size-3.5 text-slate-400 sm:block" /></button><div className="invisible absolute end-0 top-full w-52 translate-y-1 rounded-xl border border-slate-200 bg-white p-2 opacity-0 shadow-xl transition group-focus-within:visible group-focus-within:opacity-100 group-hover:visible group-hover:opacity-100"><div className="border-b border-slate-100 px-2 py-2"><p className="truncate text-sm font-bold">{user?.name}</p><p className="truncate text-xs text-slate-500" dir="ltr">{user?.email}</p></div><button onClick={onDirectionChange} className="mt-1 w-full rounded-lg px-2 py-2 text-start text-xs hover:bg-slate-50">{direction === "rtl" ? "Switch to English (LTR)" : "החלפה לעברית (RTL)"}</button><button onClick={logout} className="w-full rounded-lg px-2 py-2 text-start text-xs text-rose-600 hover:bg-rose-50">{direction === "rtl" ? "יציאה" : "Sign out"}</button></div></div>
      </div>
    </div><div className="flex gap-2 overflow-x-auto px-4 pb-3 lg:hidden"><FilterChip icon={Filter} label={direction === "rtl" ? "סינון" : "Filters"} /><FilterChip icon={Users} label={direction === "rtl" ? "צוות" : "Team"} /><FilterChip icon={CalendarDays} label={direction === "rtl" ? "תאריך" : "Date"} /></div>
  </header>;
}
function FilterChip({ icon: Icon, label }: { icon: typeof Tags; label: string }) { return <button className="flex h-9 shrink-0 items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 text-xs font-medium text-slate-600 transition hover:border-indigo-200 hover:bg-indigo-50 hover:text-indigo-700"><Icon className="size-3.5" />{label}<ChevronDown className="size-3" /></button>; }
function FilterSelect({ icon: Icon, value, onChange, label, options }: { icon: typeof Tags; value: string; onChange: (value: string) => void; label: string; options: readonly (readonly [string, string])[] }) { return <label className="relative flex h-9 items-center gap-1.5 rounded-lg border border-slate-200 bg-white ps-3 text-xs text-slate-600"><Icon className="size-3.5" /><select value={value} onChange={(event) => onChange(event.target.value)} className="h-full appearance-none bg-transparent pe-7 outline-none"><option value="">{label}</option>{options.map(([optionValue, optionLabel]) => <option key={optionValue} value={optionValue}>{optionLabel}</option>)}</select><ChevronDown className="pointer-events-none absolute end-2 size-3" /></label>; }
