import { BarChart3, Bookmark, ChevronLeft, ChevronRight, Home, Settings, ShieldCheck, Users } from "lucide-react";
import { NavLink } from "react-router";
import type { Workspace } from "@/types";
const items = [[Home,"בית סביבת העבודה","Workspace Home","/"],[Bookmark,"הסימניות שלי","My Bookmarks","/bookmarks"],[BarChart3,"אנליטיקס","Analytics","/analytics"],[Settings,"הגדרות","Settings","/settings"],[ShieldCheck,"הרשאות וניהול","Permissions / Admin","/admin"]] as const;
export function Sidebar({ collapsed, onToggle, direction, workspaces, teamFilter, onTeamFilterChange }: { collapsed: boolean; onToggle: () => void; direction: "rtl" | "ltr"; workspaces: Workspace[]; teamFilter: string; onTeamFilterChange: (value: string) => void }) {
  const CollapseIcon = direction === "rtl"
    ? (collapsed ? ChevronLeft : ChevronRight)
    : (collapsed ? ChevronRight : ChevronLeft);
  return <aside className={`workspace-sidebar sticky top-0 z-40 hidden h-dvh shrink-0 flex-col overflow-visible border-e border-black/[0.05] bg-[#f7f7f5] text-slate-600 md:flex ${collapsed ? "w-20" : "w-64"}`}>
    <button onClick={onToggle} className="absolute -end-3 top-1/2 z-50 grid size-7 -translate-y-1/2 place-items-center rounded-full border border-slate-200 bg-white text-slate-400 shadow-md transition-[color,border-color,box-shadow,transform] hover:border-blue-300 hover:text-[#0B3FC1] hover:shadow-lg active:!scale-90" aria-label={direction === "rtl" ? (collapsed ? "פתיחת התפריט" : "צמצום התפריט") : (collapsed ? "Expand sidebar" : "Collapse sidebar")} title={direction === "rtl" ? (collapsed ? "פתיחת התפריט" : "צמצום התפריט") : (collapsed ? "Expand sidebar" : "Collapse sidebar")}><CollapseIcon className={`size-3.5 transition-transform duration-300 ${collapsed ? "rotate-180" : "rotate-0"}`} /></button>
    <div className={`flex items-center gap-3 border-b border-black/[0.04] px-4 ${collapsed ? "h-20 justify-center" : "h-28"}`}><img src="/organization-logo.png" alt="לוגו הארגון" className={`${collapsed ? "size-11" : "size-16"} shrink-0 object-contain`} />{!collapsed && <div><p className="font-display text-lg font-extrabold tracking-tight text-slate-950">Linkspace</p><p className="mt-0.5 text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">Workspace</p></div>}</div>
    <nav className="flex-1 space-y-2 px-3 py-5">{items.map(([Icon,he,en,path]) => <NavLink end={path === "/"} to={path} key={en} title={collapsed ? (direction === "rtl" ? he : en) : undefined} className={({ isActive }) => `group flex h-12 w-full items-center gap-3 rounded-xl px-3 text-sm font-semibold transition ${isActive ? "bg-white text-slate-950 shadow-[0_8px_24px_rgba(15,23,42,0.06)]" : "hover:bg-white/70 hover:text-slate-950"}`}><Icon className="size-5 shrink-0 text-slate-400 group-hover:text-slate-700" />{!collapsed && <span>{direction === "rtl" ? he : en}</span>}</NavLink>)}</nav>
    <div className="m-3 border-t border-slate-200 pt-3"><div className="flex w-full items-center gap-3 rounded-xl p-2.5"><span className="grid size-9 shrink-0 place-items-center rounded-full bg-white text-slate-500 shadow-sm"><Users className="size-4.5" /></span>{!collapsed && <div className="min-w-0 flex-1"><p className="truncate text-sm font-bold text-slate-900">{workspaces[0]?.name ?? (direction === "rtl" ? "סביבת עבודה" : "Workspace")}</p><select value={teamFilter} onChange={(event) => onTeamFilterChange(event.target.value)} className="mt-1 w-full bg-transparent text-xs text-slate-400 outline-none"><option value="">{direction === "rtl" ? "כל הצוותים" : "All teams"}</option>{workspaces.flatMap((workspace) => workspace.teams).map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></div>}</div></div>
  </aside>;
}
