import { BarChart3, Bookmark, ChevronLeft, ChevronRight, Home, Link2, Settings, ShieldCheck, Users } from "lucide-react";
import { NavLink } from "react-router";
import type { Workspace } from "@/types";
const items = [[Home,"בית סביבת העבודה","Workspace Home","/"],[Bookmark,"הסימניות שלי","My Bookmarks","/bookmarks"],[BarChart3,"אנליטיקס","Analytics","/analytics"],[Settings,"הגדרות","Settings","/settings"],[ShieldCheck,"הרשאות וניהול","Permissions / Admin","/admin"]] as const;
export function Sidebar({ collapsed, onToggle, direction, workspaces, teamFilter, onTeamFilterChange }: { collapsed: boolean; onToggle: () => void; direction: "rtl" | "ltr"; workspaces: Workspace[]; teamFilter: string; onTeamFilterChange: (value: string) => void }) {
  const CollapseIcon = direction === "rtl"
    ? (collapsed ? ChevronLeft : ChevronRight)
    : (collapsed ? ChevronRight : ChevronLeft);
  return <aside className={`workspace-sidebar sticky top-0 z-40 hidden h-dvh shrink-0 flex-col border-e border-slate-200 bg-[#f7f7f5] text-slate-600 transition-[width] duration-300 md:flex ${collapsed ? "w-16" : "w-52"}`}>
    <button onClick={onToggle} className="absolute -end-3 top-1/2 z-50 grid size-6 -translate-y-1/2 place-items-center rounded-full border border-slate-200 bg-white text-slate-400 shadow-sm transition-colors hover:border-indigo-200 hover:text-indigo-600" aria-label={direction === "rtl" ? (collapsed ? "פתיחת התפריט" : "צמצום התפריט") : (collapsed ? "Expand sidebar" : "Collapse sidebar")} title={direction === "rtl" ? (collapsed ? "פתיחת התפריט" : "צמצום התפריט") : (collapsed ? "Expand sidebar" : "Collapse sidebar")}><CollapseIcon className="size-3.5" /></button>
    <div className="flex h-14 items-center gap-2.5 px-3"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-slate-950 text-white"><Link2 className="size-3.5" /></span>{!collapsed && <div><p className="text-xs font-black text-slate-900">Linkspace</p><p className="text-[8px] uppercase tracking-wider text-slate-400">Workspace</p></div>}</div>
    <nav className="flex-1 space-y-0.5 px-2 py-2">{items.map(([Icon,he,en,path]) => <NavLink end={path === "/"} to={path} key={en} title={collapsed ? (direction === "rtl" ? he : en) : undefined} className={({ isActive }) => `group flex h-9 w-full items-center gap-2.5 rounded-lg px-2.5 text-xs transition ${isActive ? "bg-white font-semibold text-slate-950 shadow-sm" : "hover:bg-white/70 hover:text-slate-950"}`}><Icon className="size-4 shrink-0 text-slate-400 group-hover:text-slate-700" />{!collapsed && <span>{direction === "rtl" ? he : en}</span>}</NavLink>)}</nav>
    <div className="m-2 border-t border-slate-200 pt-2"><div className="flex w-full items-center gap-2 rounded-lg p-2"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-white text-slate-500 shadow-sm"><Users className="size-3.5" /></span>{!collapsed && <div className="min-w-0 flex-1"><p className="truncate text-[11px] font-semibold text-slate-900">{workspaces[0]?.name ?? (direction === "rtl" ? "סביבת עבודה" : "Workspace")}</p><select value={teamFilter} onChange={(event) => onTeamFilterChange(event.target.value)} className="mt-0.5 w-full bg-transparent text-[9px] text-slate-400 outline-none"><option value="">{direction === "rtl" ? "כל הצוותים" : "All teams"}</option>{workspaces.flatMap((workspace) => workspace.teams).map((team) => <option key={team.id} value={team.id}>{team.name}</option>)}</select></div>}</div></div>
  </aside>;
}
