"""add users and project ownership

Revision ID: 33b3905280b6
Revises: 8a5694167702
Create Date: 2026-08-16 11:20:38.629495
"""
import uuid

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '33b3905280b6'
down_revision: str | None = '8a5694167702'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('microsoft_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users'))
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_microsoft_id'), 'users', ['microsoft_id'], unique=True)

    # Seed the OAuth user before making project ownership mandatory. On the
    # first Google login, the auth service will attach the provider id to this
    # existing row by matching the provider-verified email address.
    legacy_owner_id = uuid.uuid4()
    users = sa.table(
        'users',
        sa.column('id', sa.Uuid()),
        sa.column('email', sa.String(length=320)),
        sa.column('name', sa.String(length=255)),
        sa.column('google_id', sa.String(length=255)),
        sa.column('microsoft_id', sa.String(length=255)),
    )
    op.bulk_insert(
        users,
        [
            {
                'id': legacy_owner_id,
                'email': 'doronmin1112@gmail.com',
                'name': 'Doron',
                'google_id': None,
                'microsoft_id': None,
            }
        ],
    )

    op.add_column('projects', sa.Column('owner_id', sa.Uuid(), nullable=True))
    projects = sa.table(
        'projects',
        sa.column('owner_id', sa.Uuid()),
    )
    op.execute(projects.update().values(owner_id=legacy_owner_id))
    op.alter_column('projects', 'owner_id', existing_type=sa.Uuid(), nullable=False)
    op.drop_index('ix_projects_name', table_name='projects')
    op.create_index(op.f('ix_projects_owner_id'), 'projects', ['owner_id'], unique=False)
    op.create_unique_constraint('uq_projects_owner_id_name', 'projects', ['owner_id', 'name'])
    op.create_foreign_key(op.f('fk_projects_owner_id_users'), 'projects', 'users', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_projects_owner_id_users'), 'projects', type_='foreignkey')
    op.drop_constraint('uq_projects_owner_id_name', 'projects', type_='unique')
    op.drop_index(op.f('ix_projects_owner_id'), table_name='projects')
    op.create_index('ix_projects_name', 'projects', ['name'], unique=True)
    op.drop_column('projects', 'owner_id')
    op.drop_index(op.f('ix_users_microsoft_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
